### ISSUE TITLE
Where are "core.h" y "imcore.h" files?

### ISSUE THREAD

**Issue by leahycarlos21** [imlab-io/imlab_image_smoothing#2]

**Comment by cescript** [comment]
This project uses [imlab library](https://github.com/cescript/imlab_library). You can find the precompiled library and header files under [library](https://github.com/cescript/imlab_library/tree/master/library) folder . If the precompiled library doesn't work for you, you should rebuild the library first. After creating the library files, you should set the IMLAB_LIBRARY_DIRECTORY variable in CMakeList.txt to the newly created library directory.

**Comment by leahycarlos21** [comment]
Appreciate it!
